# Shorten the uptime format
long_uptime = false 

# Shorten the shell output
long_shell = false 

# Lengthen shell output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Specify the theme to use
# Accepted values (case-insensitive):
#   - Hydrogen
#   - Helium
#   - Lithium
#   - Beryllium
#   - Boron
#
# Custom themes are also supported, they should be placed
# in $XDG_DATA_HOME/macchina/themes and must be a JSON file.
# 
# To set 'foobar' as a theme, place foobar.json 
# in $XDG_DATA_HOME/macchina/themes
# and set theme = "foobar" (case-sensitive)
theme = "Dracula"
